project:
  type: website
  output-dir: "_site"
  # DO NOT USE lib-dir
  resources:
    - .nojekyll
    - CNAME
    - "/res/*"
    - "/libs/*"
    - "/content/**/*.pdf"
  render:
    - "*.qmd"
    - "!TODO.md"
    - "!LICENSE.md"
    - "!test/"
    - "!src/"
    - "!libs/"

website:
  title: "Marc-Aurèle Rivière"
  description: "Cognitive & Data Scientist: Perception, HMI, VR ◈ R, Stats, Bayes"
  image: res/avatar.jpg
  favicon: res/favicon.png
  site-url: 'https://ma-riviere.com'
  repo-url: https://github.com/ma-riviere/ma-riviere.com
  
  ### Analytics ###
  google-analytics:
    tracking-id: "G-QP3K4HM02B"
  cookie-consent:
    type: implied
  
  ### Sharing ###
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@mariviere1"
    card-style: summary
  
  ### Search ###
  search:
    location: navbar
    type: overlay
    collapse-after: 10
    show-item-context: true
    # show-item-parent: breadcrumbs
  
  ### Navigation ###
  # page-navigation: true
  bread-crumbs: true
  
  navbar:
    # logo: res/hexacode.svg
    # logo-alt: "Hexagon containing a neuron"
    pinned: true
    collapse: true
    collapse-below: md
    left:
      - text: "{{< fa business-time >}} Projects"
        file: content/projects/index.qmd
        aria-label: "A list of the projects I was or am involved in"
      - text: "{{< fa book >}} Publications"
        file: content/pubs/index.qmd
        aria-label: "A list of my scientific writings"
      - text: "{{< iconify file-icons keynote height=20px >}} Communications"
        file: content/sci-com/index.qmd
        aria-label: "A list of my talks and outreach activities"
      - text: "Code"
        icon: code-slash
        file: content/code/index.qmd
        aria-label: "A list of my R and stats projects"
    right:
      - text: "{{< fa user-tie >}} About Me"
        file: content/about.qmd
        aria-label: "About Me"
      - icon: rss
        file: content/code/index.xml
        aria-label: "My blog's RSS feed"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ma-riviere/ma-riviere.com/
            aria-label: "Website's source code"
          - text: GitHub Profile
            url: https://github.com/ma-riviere/
            aria-label: "My GitHub profile"
  
  ## Auto-sidebar: https://quarto.org/docs/websites/website-navigation.html#auto-generation
  sidebar: false
  # sidebar:
  #   - id: code
  #     title: "Code" # Will auto-link to page with same title ?
  #     style: floating
  #     alignment: left
  #     collapse-level: 3
  #     tools: false
  #     contents:
  #       - section: "R"
  #         contents:
  #           - section: "Data Wrangling"
  #           - text: "---"
  #           - section: "Modeling"
  
  ### Footer ###
  page-footer:
    border: true
    left: 
      - text: "© 2021-2023, Marc-Aurèle Rivière"
        href: LICENSE.md
        aria-label: "Website's license"
    right:
      - text: "Made with Quarto ♥️"
        href: https://quarto.org/
        aria-label: "Quarto's website"


from: markdown+emoji
bibliography: res/refs.bib
csl: res/apa.csl
link-citations: true

citation: false
comments: false
toc: false

format:
  html:
    theme:
      light: [default, libs/css/light.scss]
      dark: [libs/css/dark.scss]
    css: libs/css/style.css
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
    df-print: paged
    fig-align: center
    fig-dpi: 500
    fig-format: svg
    # fig-cap-location: bottom
    anchor-sections: true
    footnotes-hover: true
    code-link: true
    code-copy: hover
    code-block-bg: true
    code-overflow: scroll
    highlight-style:
      light: libs/highlight-styles/light.theme
      dark: libs/highlight-styles/dark.theme
    link-external-newwindow: true

filters:
  - lightbox

lightbox:
  match: auto

engine: knitr

knitr:
  opts_chunk:
    warning: false
    message: false
    fig.align: center
    dpi: 500
    dev: svg
    dev.args:
      bg: transparent
    # R.options:
    #   scipen: 999

execute:
  warning: false
  message: false
  cache: false
  freeze: auto

editor: source