project:
  type: website
  output-dir: "_site"
  # DO NOT USE lib-dir
  resources:
    - .nojekyll
    - CNAME
    - "/res/*"
    - "/libs/*"
    - "/content/**/*.pdf"
  render:
    - "*.qmd"
    - "!TODO.md"
    - "!LICENSE.md"
    - "!test/"
    - "!src/"
    - "!libs/"

website:
  title: "Marc-Aurèle Rivière"
  description: "R Programmer | Data Scientist | Cognitive Neuroscientist"
  image: res/avatar.jpg
  favicon: res/hexabrain.svg
  site-url: 'https://ma-riviere.com'
  repo-url: https://github.com/ma-riviere/ma-riviere.com
  
  ### Analytics ###
  google-analytics:
    tracking-id: "G-QP3K4HM02B"
  cookie-consent:
    type: implied
  
  ### Sharing ###
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@mariviere1"
    card-style: summary
  
  ### Search ###
  search:
    location: navbar
    type: overlay
    collapse-after: 2
    show-item-context: true
  
  ### Navigation ###
  back-to-top-navigation: true
  page-navigation: true
  bread-crumbs: true
  
  ### Navbar ###
  navbar:
    logo: res/hexabrain.svg
    logo-alt: "Stylized depiction of a brain inside a hexagon"
    pinned: true
    collapse: true
    collapse-below: md
    toggle-position: left
    left:
      - text: "Projects"
        icon: journal-code
        file: content/projects/index.qmd
        aria-label: "A curated list of code-related projects I was or am involved in"
      - text: "Publications"
        icon: file-text
        file: content/pubs/index.qmd
        aria-label: "A list of my peer-reviewed scientific publications"
      - text: "Blog"
        icon: braces
        file: content/blog/index.qmd
        aria-label: "A list of blog posts related to R, stats, and data science"
    right:
      - text: "About Me"
        icon: person-vcard
        file: content/about.qmd
        aria-label: "About Me"
      - icon: rss
        file: content/blog/index.xml
        aria-label: "My blog's RSS feed"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ma-riviere/ma-riviere.com/
            aria-label: "Website's source code"
          - text: GitHub Profile
            url: https://github.com/ma-riviere/
            aria-label: "My GitHub profile"
  
  ### Sidebar ###
  sidebar: false
  
  ### Footer ###
  page-footer:
    border: true
    left: 
      - text: "© 2021-{{< now year >}}, Marc-Aurèle Rivière"
        href: LICENSE.md
        aria-label: "Website's license"
    right:
      - text: "Made with Quarto ♥️"
        href: https://quarto.org/
        aria-label: "Quarto's website"

## Bibliography ##

bibliography: 
  - res/refs.bib
  - res/software.bib
csl: res/apa.csl
link-citations: true

citation: false

## Image options ##

lightbox: true

from: markdown+emoji
comments: false
toc: false

## Format options ##

format:
  html:
    theme:
      light: [default, libs/css/light.scss]
      dark: [libs/css/dark.scss]
    css: libs/css/style.css
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
    df-print: paged
    fig-align: center
    fig-dpi: 500
    fig-format: svg
    # fig-cap-location: bottom
    anchor-sections: true
    footnotes-hover: true
    code-link: true
    code-copy: hover
    code-block-bg: true
    code-overflow: scroll
    highlight-style:
      light: libs/highlight-styles/light.theme
      dark: libs/highlight-styles/dark.theme
    link-external-newwindow: true
    link-external-icon: true
    html-math-method: webtex

## Execution / R options ##

engine: knitr

knitr:
  opts_chunk:
    warning: false
    message: false
    fig.align: center
    dpi: 500
    dev: svg
    dev.args:
      bg: transparent
    # R.options:
    #   scipen: 999
  opts_knit:
    verbose: false

execute:
  warning: false
  message: false
  cache: false
  freeze: auto

editor: source